### PR TITLE
prevent newlines being added by OS command stdout

### LINKED ISSUE #48: gofmt produces empty new line
I like the package very much. It is only that there is this one very annoying detail that all go files that are formatted using this package end up having an empty line at the end of the file. This should be fixed IMO. As you can see in the screenshot I made from the developer console, the property `r.stdout` holds the formatted source code having the trailing newline attached. The beginning of the formatted source code string is correct, the end is not. 

```
"package main

import "fmt"

func main() {
    fmt.Printf("%#vn", "foo")
}
"
```

This is how it should look like. Note the difference of the end of the code.

```
"package main

import "fmt"

func main() {
    fmt.Printf("%#vn", "foo")
}"
```

screen shot 2016-10-21 at 16 42 28

Also note that I am using `goimports`, but `gofmt` is doing the same. In fact, it is not the go tools that produce this, but the OS command execution and stdout capturing itself. I think a simple check for a newline at the end and removing it in case it is there should be good enough. This is the result now. 

screen shot 2016-10-21 at 16 58 07

### PR DESCRIPTION
**Pull request by xh3b4sd**
This PR fixes https://github.com/joefitzgerald/gofmt/issues/48.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I will fix the tests and add a new one in case we agree on the desire to have this change merged in.

**Comment by joefitzgerald** [comment]
Atom already adds a new line and trims spurious newlines from the end of a file on save. Are you really seeing more than 1 blank line at the end of a file?

**Comment by xh3b4sd** [comment]
The whitespace package has an option to ensure a trailing empty new line. I
disabled this. All files are fine, except the ones formatted using the
gofmt package in Atom. Is it maybe because of the package execution order?
Maybe the whitespace plugin kicks in before gofmt. In any case, the current
behavior is annoying. Do you experience another behaviour? Do your go files
not have trailing empty new lines when using this package here?

**Comment by xh3b4sd** [comment]
I think this PR is wrong and does not fix anything. I am closing this now. Thanks for listening.

**Pull request closed without merging**
